swagger: '2.0'
info:
  description: API para el control de listas con periodos perdidos 
  version: '1.0'
  title: API Periodos Perdidos
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: miguel.gajardomunoz@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8081'
basePath: /periodosperdidos
tags:
  - name: periodosperdidos
    description: Lista de periodos perdidos
schemes:
  - http
paths:
  /api:
    get:
      tags:
        - periodosperdidos
      summary: Lista de periodos perdidos
      operationId: periodosperdidos
      produces:
        - application/json
      responses:
        '200':
          description: OK - Listas Obtenidas
          schema:
            $ref: '#/definitions/PeriodoPerdido'
        '201':
          description: Creado
        '400':
          description: Bad Request
        '401':
          description: No Autorizado
        '403':
          description: Prohibido
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
definitions:
  PeriodoPerdido:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
      fechasFaltantes:
        type: array
        items:
          type: string
          format: date
externalDocs:
  description: Especificación de swagger
  url: 'https://swagger.io/docs/specification/about/'
